/* Generated by Yosys 0.47+61 (git sha1 81011ad92, clang++ 18.1.8 -fPIC -O3) */

module disp_cmp_13_64_7 #(parameter WIDTH_SR = 153)(i_data_c1, i_data_d1, i_data_c2, i_data_d2, o_data_c, o_data_d, i_FI_CONTROL_PORT, i_SI, o_SI);
  input i_SI;
  input [3:0] i_FI_CONTROL_PORT;
  output o_SI;
  wire [WIDTH_SR-1:0] o_SR;
  assign o_SI = o_SR[0];
  wire temp__nw_000_;
  wire temp__nw_001_;
  wire temp__nw_002_;
  wire temp__nw_003_;
  wire temp__nw_004_;
  wire temp__nw_005_;
  wire temp__nw_006_;
  wire temp__nw_007_;
  wire temp__nw_008_;
  wire temp__nw_009_;
  wire temp__nw_010_;
  wire temp__nw_011_;
  wire temp__nw_012_;
  wire temp__nw_013_;
  wire temp__nw_014_;
  wire temp__nw_015_;
  wire temp__nw_016_;
  wire temp__nw_017_;
  wire temp__nw_018_;
  wire temp__nw_019_;
  wire temp__nw_020_;
  wire temp__nw_021_;
  wire temp__nw_022_;
  wire temp__nw_023_;
  wire temp__nw_024_;
  wire [30:0] temp__nw_025_;
  wire temp__nw_026_;
  wire temp__nw_027_;
  wire temp__nw_028_;
  wire temp__nw_029_;
  wire temp__nw_030_;
  wire temp__nw_031_;
  wire temp__nw_032_;
  wire temp__nw_033_;
  wire temp__nw_034_;
  wire temp__nw_035_;
  wire temp__nw_036_;
  wire temp__nw_037_;
  wire temp__nw_038_;
  wire temp__nw_039_;
  wire [30:0] temp__nw_040_;
  wire temp__nw_041_;
  wire temp__nw_042_;
  wire temp__nw_043_;
  wire temp__nw_044_;
  wire temp__nw_045_;
  wire temp__nw_046_;
  wire temp__nw_047_;
  wire temp__nw_048_;
  wire temp__nw_049_;
  wire temp__nw_050_;
  wire temp__nw_051_;
  wire temp__nw_052_;
  wire temp__nw_053_;
  wire temp__nw_054_;
  wire temp__nw_055_;
  wire temp__nw_056_;
  wire temp__nw_057_;
  wire temp__nw_058_;
  wire temp__nw_059_;
  wire temp__nw_060_;
  wire temp__nw_061_;
  wire temp__nw_062_;
  wire temp__nw_063_;
  wire temp__nw_064_;
  wire temp__nw_065_;
  wire temp__nw_066_;
  wire temp__nw_067_;
  wire temp__nw_068_;
  wire temp__nw_069_;
  wire temp__nw_070_;
  wire temp__nw_071_;
  wire [11:0] temp_o_data_c;
  wire [6:0] temp_o_data_d;
  wire _nw_000_;
  wire _nw_001_;
  wire _nw_002_;
  wire _nw_003_;
  wire _nw_004_;
  wire _nw_005_;
  wire _nw_006_;
  wire _nw_007_;
  wire _nw_008_;
  wire _nw_009_;
  wire _nw_010_;
  wire _nw_011_;
  wire _nw_012_;
  wire _nw_013_;
  wire _nw_014_;
  wire _nw_015_;
  wire _nw_016_;
  wire _nw_017_;
  wire _nw_018_;
  wire _nw_019_;
  wire _nw_020_;
  wire _nw_021_;
  wire _nw_022_;
  wire _nw_023_;
  wire _nw_024_;
  wire [30:8] _nw_025_;
  wire _nw_026_;
  wire _nw_027_;
  wire _nw_028_;
  wire _nw_029_;
  wire _nw_030_;
  wire _nw_031_;
  wire _nw_032_;
  wire _nw_033_;
  wire _nw_034_;
  wire _nw_035_;
  wire _nw_036_;
  wire _nw_037_;
  wire _nw_038_;
  wire _nw_039_;
  wire [30:0] _nw_040_;
  wire _nw_041_;
  wire _nw_042_;
  wire _nw_043_;
  wire _nw_044_;
  wire _nw_045_;
  wire _nw_046_;
  wire _nw_047_;
  wire _nw_048_;
  wire _nw_049_;
  wire _nw_050_;
  wire _nw_051_;
  wire _nw_052_;
  wire _nw_053_;
  wire _nw_054_;
  wire _nw_055_;
  wire _nw_056_;
  wire _nw_057_;
  wire _nw_058_;
  wire _nw_059_;
  wire _nw_060_;
  wire _nw_061_;
  wire _nw_062_;
  wire _nw_063_;
  wire _nw_064_;
  wire _nw_065_;
  wire _nw_066_;
  wire _nw_067_;
  wire _nw_068_;
  wire _nw_069_;
  wire _nw_070_;
  wire _nw_071_;
  input [11:0] i_data_c1;
  wire [11:0] i_data_c1;
  input [11:0] i_data_c2;
  wire [11:0] i_data_c2;
  input [6:0] i_data_d1;
  wire [6:0] i_data_d1;
  input [6:0] i_data_d2;
  wire [6:0] i_data_d2;
  output [11:0] o_data_c;
  wire [11:0] o_data_c;
  output [6:0] o_data_d;
  wire [6:0] o_data_d;
  assign temp__nw_040_[30] = ~_nw_025_[30];
  assign temp__nw_000_ = _nw_028_ & _nw_031_;
  assign temp__nw_006_ = _nw_000_ & _nw_001_;
  assign temp__nw_009_ = _nw_006_ & _nw_007_;
  assign temp__nw_010_ = _nw_009_ & _nw_008_;
  assign temp_o_data_d[0] = _nw_053_ ? i_data_d1[0] : i_data_d2[0];
  assign temp_o_data_d[1] = _nw_053_ ? i_data_d1[1] : i_data_d2[1];
  assign temp_o_data_d[2] = _nw_053_ ? i_data_d1[2] : i_data_d2[2];
  assign temp_o_data_d[3] = _nw_053_ ? i_data_d1[3] : i_data_d2[3];
  assign temp_o_data_d[4] = _nw_053_ ? i_data_d1[4] : i_data_d2[4];
  assign temp_o_data_d[5] = _nw_053_ ? i_data_d1[5] : i_data_d2[5];
  assign temp_o_data_d[6] = _nw_053_ ? i_data_d1[6] : i_data_d2[6];
  assign temp_o_data_c[0] = _nw_053_ ? i_data_c1[0] : i_data_c2[0];
  assign temp_o_data_c[1] = _nw_053_ ? i_data_c1[1] : i_data_c2[1];
  assign temp_o_data_c[2] = _nw_053_ ? i_data_c1[2] : i_data_c2[2];
  assign temp_o_data_c[3] = _nw_053_ ? i_data_c1[3] : i_data_c2[3];
  assign temp_o_data_c[4] = _nw_053_ ? i_data_c1[4] : i_data_c2[4];
  assign temp_o_data_c[5] = _nw_053_ ? i_data_c1[5] : i_data_c2[5];
  assign temp_o_data_c[6] = _nw_053_ ? i_data_c1[6] : i_data_c2[6];
  assign temp_o_data_c[7] = _nw_053_ ? i_data_c1[7] : i_data_c2[7];
  assign temp_o_data_c[8] = _nw_053_ ? i_data_c1[8] : i_data_c2[8];
  assign temp_o_data_c[9] = _nw_053_ ? i_data_c1[9] : i_data_c2[9];
  assign temp_o_data_c[10] = _nw_053_ ? i_data_c1[10] : i_data_c2[10];
  assign temp_o_data_c[11] = _nw_053_ ? i_data_c1[11] : i_data_c2[11];
  assign temp__nw_011_ = ~i_data_c2[0];
  assign temp__nw_014_ = ~i_data_c2[1];
  assign temp__nw_015_ = ~i_data_c2[2];
  assign temp__nw_016_ = ~i_data_c2[3];
  assign temp__nw_017_ = ~i_data_c2[4];
  assign temp__nw_018_ = ~i_data_c2[5];
  assign temp__nw_019_ = ~i_data_c2[6];
  assign temp__nw_020_ = ~i_data_c2[7];
  assign temp__nw_021_ = ~i_data_c2[8];
  assign temp__nw_022_ = ~i_data_c2[9];
  assign temp__nw_012_ = ~i_data_c2[10];
  assign temp__nw_013_ = ~i_data_c2[11];
  assign temp__nw_053_ = _nw_040_[30] | _nw_010_;
  assign temp__nw_041_ = i_data_c1[0] & _nw_011_;
  assign temp__nw_044_ = i_data_c1[1] & _nw_014_;
  assign temp__nw_045_ = i_data_c1[2] & _nw_015_;
  assign temp__nw_046_ = i_data_c1[3] & _nw_016_;
  assign temp__nw_047_ = i_data_c1[4] & _nw_017_;
  assign temp__nw_048_ = i_data_c1[5] & _nw_018_;
  assign temp__nw_049_ = i_data_c1[6] & _nw_019_;
  assign temp__nw_050_ = i_data_c1[7] & _nw_020_;
  assign temp__nw_051_ = i_data_c1[8] & _nw_021_;
  assign temp__nw_052_ = i_data_c1[9] & _nw_022_;
  assign temp__nw_042_ = i_data_c1[10] & _nw_012_;
  assign temp__nw_043_ = i_data_c1[11] & _nw_013_;
  assign temp__nw_028_ = i_data_c1[0] ^ _nw_011_;
  assign temp__nw_031_ = i_data_c1[1] ^ _nw_014_;
  assign temp__nw_032_ = i_data_c1[2] ^ _nw_015_;
  assign temp__nw_033_ = i_data_c1[3] ^ _nw_016_;
  assign temp__nw_034_ = i_data_c1[4] ^ _nw_017_;
  assign temp__nw_035_ = i_data_c1[5] ^ _nw_018_;
  assign temp__nw_036_ = i_data_c1[6] ^ _nw_019_;
  assign temp__nw_037_ = i_data_c1[7] ^ _nw_020_;
  assign temp__nw_038_ = i_data_c1[8] ^ _nw_021_;
  assign temp__nw_039_ = i_data_c1[9] ^ _nw_022_;
  assign temp__nw_029_ = i_data_c1[10] ^ _nw_012_;
  assign temp__nw_030_ = i_data_c1[11] ^ _nw_013_;
  assign temp__nw_025_[30] = _nw_064_ | _nw_065_;
  assign temp__nw_027_ = _nw_071_ | _nw_063_;
  assign temp__nw_064_ = _nw_070_ | _nw_062_;
  assign temp__nw_071_ = _nw_068_ | _nw_061_;
  assign temp__nw_026_ = _nw_066_ | _nw_060_;
  assign temp__nw_070_ = _nw_043_ | _nw_059_;
  assign temp__nw_069_ = _nw_052_ | _nw_058_;
  assign temp__nw_068_ = _nw_050_ | _nw_057_;
  assign temp__nw_067_ = _nw_048_ | _nw_056_;
  assign temp__nw_066_ = _nw_046_ | _nw_055_;
  assign temp__nw_024_ = _nw_044_ | _nw_054_;
  assign temp__nw_023_ = _nw_041_ | _nw_028_;
  assign temp__nw_065_ = _nw_008_ & _nw_027_;
  assign temp__nw_008_ = _nw_005_ & _nw_004_;
  assign temp__nw_007_ = _nw_003_ & _nw_002_;
  assign temp__nw_005_ = _nw_030_ & _nw_029_;
  assign temp__nw_004_ = _nw_039_ & _nw_038_;
  assign temp__nw_003_ = _nw_037_ & _nw_036_;
  assign temp__nw_002_ = _nw_035_ & _nw_034_;
  assign temp__nw_001_ = _nw_033_ & _nw_032_;
  assign temp__nw_063_ = _nw_007_ & _nw_026_;
  assign temp__nw_062_ = _nw_005_ & _nw_069_;
  assign temp__nw_061_ = _nw_003_ & _nw_067_;
  assign temp__nw_060_ = _nw_001_ & _nw_024_;
  assign temp__nw_059_ = _nw_030_ & _nw_042_;
  assign temp__nw_058_ = _nw_039_ & _nw_051_;
  assign temp__nw_057_ = _nw_037_ & _nw_049_;
  assign temp__nw_056_ = _nw_035_ & _nw_047_;
  assign temp__nw_055_ = _nw_033_ & _nw_045_;
  assign temp__nw_054_ = _nw_031_ & _nw_023_;
  assign temp__nw_025_[29:11] = { _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30], _nw_025_[30] };
  assign temp__nw_040_[29:12] = { _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30], _nw_040_[30] };
super_sabouter #(.WIDTH(1)) SS0(
                  .i_sig(temp__nw_000_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[0:0]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_000_)
                  );
super_sabouter #(.WIDTH(1)) SS1(
                  .i_sig(temp__nw_001_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[1:1]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_001_)
                  );
super_sabouter #(.WIDTH(1)) SS2(
                  .i_sig(temp__nw_002_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[2:2]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_002_)
                  );
super_sabouter #(.WIDTH(1)) SS3(
                  .i_sig(temp__nw_003_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[3:3]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_003_)
                  );
super_sabouter #(.WIDTH(1)) SS4(
                  .i_sig(temp__nw_004_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[4:4]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_004_)
                  );
super_sabouter #(.WIDTH(1)) SS5(
                  .i_sig(temp__nw_005_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[5:5]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_005_)
                  );
super_sabouter #(.WIDTH(1)) SS6(
                  .i_sig(temp__nw_006_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[6:6]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_006_)
                  );
super_sabouter #(.WIDTH(1)) SS7(
                  .i_sig(temp__nw_007_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[7:7]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_007_)
                  );
super_sabouter #(.WIDTH(1)) SS8(
                  .i_sig(temp__nw_008_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[8:8]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_008_)
                  );
super_sabouter #(.WIDTH(1)) SS9(
                  .i_sig(temp__nw_009_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[9:9]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_009_)
                  );
super_sabouter #(.WIDTH(1)) SS10(
                  .i_sig(temp__nw_010_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[10:10]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_010_)
                  );
super_sabouter #(.WIDTH(1)) SS11(
                  .i_sig(temp__nw_011_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[11:11]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_011_)
                  );
super_sabouter #(.WIDTH(1)) SS12(
                  .i_sig(temp__nw_012_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[12:12]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_012_)
                  );
super_sabouter #(.WIDTH(1)) SS13(
                  .i_sig(temp__nw_013_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[13:13]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_013_)
                  );
super_sabouter #(.WIDTH(1)) SS14(
                  .i_sig(temp__nw_014_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[14:14]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_014_)
                  );
super_sabouter #(.WIDTH(1)) SS15(
                  .i_sig(temp__nw_015_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[15:15]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_015_)
                  );
super_sabouter #(.WIDTH(1)) SS16(
                  .i_sig(temp__nw_016_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[16:16]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_016_)
                  );
super_sabouter #(.WIDTH(1)) SS17(
                  .i_sig(temp__nw_017_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[17:17]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_017_)
                  );
super_sabouter #(.WIDTH(1)) SS18(
                  .i_sig(temp__nw_018_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[18:18]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_018_)
                  );
super_sabouter #(.WIDTH(1)) SS19(
                  .i_sig(temp__nw_019_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[19:19]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_019_)
                  );
super_sabouter #(.WIDTH(1)) SS20(
                  .i_sig(temp__nw_020_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[20:20]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_020_)
                  );
super_sabouter #(.WIDTH(1)) SS21(
                  .i_sig(temp__nw_021_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[21:21]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_021_)
                  );
super_sabouter #(.WIDTH(1)) SS22(
                  .i_sig(temp__nw_022_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[22:22]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_022_)
                  );
super_sabouter #(.WIDTH(1)) SS23(
                  .i_sig(temp__nw_023_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[23:23]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_023_)
                  );
super_sabouter #(.WIDTH(1)) SS24(
                  .i_sig(temp__nw_024_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[24:24]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_024_)
                  );
super_sabouter #(.WIDTH(31)) SS25(
                  .i_sig(temp__nw_025_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[55:25]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_025_)
                  );
super_sabouter #(.WIDTH(1)) SS26(
                  .i_sig(temp__nw_026_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[56:56]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_026_)
                  );
super_sabouter #(.WIDTH(1)) SS27(
                  .i_sig(temp__nw_027_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[57:57]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_027_)
                  );
super_sabouter #(.WIDTH(1)) SS28(
                  .i_sig(temp__nw_028_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[58:58]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_028_)
                  );
super_sabouter #(.WIDTH(1)) SS29(
                  .i_sig(temp__nw_029_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[59:59]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_029_)
                  );
super_sabouter #(.WIDTH(1)) SS30(
                  .i_sig(temp__nw_030_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[60:60]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_030_)
                  );
super_sabouter #(.WIDTH(1)) SS31(
                  .i_sig(temp__nw_031_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[61:61]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_031_)
                  );
super_sabouter #(.WIDTH(1)) SS32(
                  .i_sig(temp__nw_032_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[62:62]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_032_)
                  );
super_sabouter #(.WIDTH(1)) SS33(
                  .i_sig(temp__nw_033_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[63:63]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_033_)
                  );
super_sabouter #(.WIDTH(1)) SS34(
                  .i_sig(temp__nw_034_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[64:64]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_034_)
                  );
super_sabouter #(.WIDTH(1)) SS35(
                  .i_sig(temp__nw_035_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[65:65]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_035_)
                  );
super_sabouter #(.WIDTH(1)) SS36(
                  .i_sig(temp__nw_036_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[66:66]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_036_)
                  );
super_sabouter #(.WIDTH(1)) SS37(
                  .i_sig(temp__nw_037_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[67:67]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_037_)
                  );
super_sabouter #(.WIDTH(1)) SS38(
                  .i_sig(temp__nw_038_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[68:68]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_038_)
                  );
super_sabouter #(.WIDTH(1)) SS39(
                  .i_sig(temp__nw_039_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[69:69]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_039_)
                  );
super_sabouter #(.WIDTH(31)) SS40(
                  .i_sig(temp__nw_040_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[100:70]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_040_)
                  );
super_sabouter #(.WIDTH(1)) SS41(
                  .i_sig(temp__nw_041_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[101:101]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_041_)
                  );
super_sabouter #(.WIDTH(1)) SS42(
                  .i_sig(temp__nw_042_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[102:102]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_042_)
                  );
super_sabouter #(.WIDTH(1)) SS43(
                  .i_sig(temp__nw_043_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[103:103]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_043_)
                  );
super_sabouter #(.WIDTH(1)) SS44(
                  .i_sig(temp__nw_044_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[104:104]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_044_)
                  );
super_sabouter #(.WIDTH(1)) SS45(
                  .i_sig(temp__nw_045_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[105:105]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_045_)
                  );
super_sabouter #(.WIDTH(1)) SS46(
                  .i_sig(temp__nw_046_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[106:106]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_046_)
                  );
super_sabouter #(.WIDTH(1)) SS47(
                  .i_sig(temp__nw_047_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[107:107]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_047_)
                  );
super_sabouter #(.WIDTH(1)) SS48(
                  .i_sig(temp__nw_048_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[108:108]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_048_)
                  );
super_sabouter #(.WIDTH(1)) SS49(
                  .i_sig(temp__nw_049_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[109:109]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_049_)
                  );
super_sabouter #(.WIDTH(1)) SS50(
                  .i_sig(temp__nw_050_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[110:110]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_050_)
                  );
super_sabouter #(.WIDTH(1)) SS51(
                  .i_sig(temp__nw_051_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[111:111]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_051_)
                  );
super_sabouter #(.WIDTH(1)) SS52(
                  .i_sig(temp__nw_052_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[112:112]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_052_)
                  );
super_sabouter #(.WIDTH(1)) SS53(
                  .i_sig(temp__nw_053_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[113:113]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_053_)
                  );
super_sabouter #(.WIDTH(1)) SS54(
                  .i_sig(temp__nw_054_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[114:114]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_054_)
                  );
super_sabouter #(.WIDTH(1)) SS55(
                  .i_sig(temp__nw_055_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[115:115]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_055_)
                  );
super_sabouter #(.WIDTH(1)) SS56(
                  .i_sig(temp__nw_056_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[116:116]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_056_)
                  );
super_sabouter #(.WIDTH(1)) SS57(
                  .i_sig(temp__nw_057_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[117:117]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_057_)
                  );
super_sabouter #(.WIDTH(1)) SS58(
                  .i_sig(temp__nw_058_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[118:118]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_058_)
                  );
super_sabouter #(.WIDTH(1)) SS59(
                  .i_sig(temp__nw_059_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[119:119]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_059_)
                  );
super_sabouter #(.WIDTH(1)) SS60(
                  .i_sig(temp__nw_060_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[120:120]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_060_)
                  );
super_sabouter #(.WIDTH(1)) SS61(
                  .i_sig(temp__nw_061_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[121:121]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_061_)
                  );
super_sabouter #(.WIDTH(1)) SS62(
                  .i_sig(temp__nw_062_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[122:122]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_062_)
                  );
super_sabouter #(.WIDTH(1)) SS63(
                  .i_sig(temp__nw_063_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[123:123]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_063_)
                  );
super_sabouter #(.WIDTH(1)) SS64(
                  .i_sig(temp__nw_064_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[124:124]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_064_)
                  );
super_sabouter #(.WIDTH(1)) SS65(
                  .i_sig(temp__nw_065_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[125:125]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_065_)
                  );
super_sabouter #(.WIDTH(1)) SS66(
                  .i_sig(temp__nw_066_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[126:126]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_066_)
                  );
super_sabouter #(.WIDTH(1)) SS67(
                  .i_sig(temp__nw_067_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[127:127]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_067_)
                  );
super_sabouter #(.WIDTH(1)) SS68(
                  .i_sig(temp__nw_068_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[128:128]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_068_)
                  );
super_sabouter #(.WIDTH(1)) SS69(
                  .i_sig(temp__nw_069_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[129:129]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_069_)
                  );
super_sabouter #(.WIDTH(1)) SS70(
                  .i_sig(temp__nw_070_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[130:130]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_070_)
                  );
super_sabouter #(.WIDTH(1)) SS71(
                  .i_sig(temp__nw_071_),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[131:131]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(_nw_071_)
                  );
super_sabouter #(.WIDTH(12)) SS72(
                  .i_sig(temp_o_data_c),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[143:132]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(o_data_c)
                  );
super_sabouter #(.WIDTH(7)) SS73(
                  .i_sig(temp_o_data_d),
                  .i_en_super_sabouter(i_FI_CONTROL_PORT[1]),
                  .i_en_basic_sabouter(o_SR[150:144]),
                  .i_ctrl(o_SR[152:151]),
                  .o_sig(o_data_d)
                  );
shift_register #(.WIDTH(WIDTH_SR)) SR(
                    .i_CLK(i_FI_CONTROL_PORT[3]),
                    .i_RST(i_FI_CONTROL_PORT[2]),
                    .i_EN(i_FI_CONTROL_PORT[0]),
                    .i_SI(i_SI),
                    .o_DATA(o_SR)
                    );
endmodule
