/* Generated by Yosys 0.47+61 (git sha1 81011ad92, clang++ 18.1.8 -fPIC -O3) */

module \$paramod$3252fe89cd119cf7c3ef25b9a50779b2d8d95ba3\DSR_left_N_S_sbtr #(parameter WIDTH_SR = 66) (a, b, c, i_FI_CONTROL_PORT, i_SI, o_SI);
  input i_SI;
  input [3:0] i_FI_CONTROL_PORT;
  output o_SI;
  wire [WIDTH_SR-1:0] o_SR;
  assign o_SI = o_SR[0];
  wire [15:0] temp_c ;
  wire \temp_tmp[0][0] ;
  wire \temp_tmp[0][10] ;
  wire \temp_tmp[0][11] ;
  wire \temp_tmp[0][12] ;
  wire \temp_tmp[0][13] ;
  wire \temp_tmp[0][14] ;
  wire \temp_tmp[0][15] ;
  wire \temp_tmp[0][1] ;
  wire \temp_tmp[0][2] ;
  wire \temp_tmp[0][3] ;
  wire \temp_tmp[0][4] ;
  wire \temp_tmp[0][5] ;
  wire \temp_tmp[0][6] ;
  wire \temp_tmp[0][7] ;
  wire \temp_tmp[0][8] ;
  wire \temp_tmp[0][9] ;
  wire \temp_tmp[1][0] ;
  wire \temp_tmp[1][10] ;
  wire \temp_tmp[1][11] ;
  wire \temp_tmp[1][12] ;
  wire \temp_tmp[1][13] ;
  wire \temp_tmp[1][14] ;
  wire \temp_tmp[1][15] ;
  wire \temp_tmp[1][1] ;
  wire \temp_tmp[1][2] ;
  wire \temp_tmp[1][3] ;
  wire \temp_tmp[1][4] ;
  wire \temp_tmp[1][5] ;
  wire \temp_tmp[1][6] ;
  wire \temp_tmp[1][7] ;
  wire \temp_tmp[1][8] ;
  wire \temp_tmp[1][9] ;
  wire \temp_tmp[2][0] ;
  wire \temp_tmp[2][10] ;
  wire \temp_tmp[2][11] ;
  wire \temp_tmp[2][12] ;
  wire \temp_tmp[2][13] ;
  wire \temp_tmp[2][14] ;
  wire \temp_tmp[2][15] ;
  wire \temp_tmp[2][1] ;
  wire \temp_tmp[2][2] ;
  wire \temp_tmp[2][3] ;
  wire \temp_tmp[2][4] ;
  wire \temp_tmp[2][5] ;
  wire \temp_tmp[2][6] ;
  wire \temp_tmp[2][7] ;
  wire \temp_tmp[2][8] ;
  wire \temp_tmp[2][9] ;
  input [15:0] a;
  wire [15:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [15:0] c;
  wire [15:0] c;
  wire \tmp[0][0] ;
  wire \tmp[0][10] ;
  wire \tmp[0][11] ;
  wire \tmp[0][12] ;
  wire \tmp[0][13] ;
  wire \tmp[0][14] ;
  wire \tmp[0][15] ;
  wire \tmp[0][1] ;
  wire \tmp[0][2] ;
  wire \tmp[0][3] ;
  wire \tmp[0][4] ;
  wire \tmp[0][5] ;
  wire \tmp[0][6] ;
  wire \tmp[0][7] ;
  wire \tmp[0][8] ;
  wire \tmp[0][9] ;
  wire \tmp[1][0] ;
  wire \tmp[1][10] ;
  wire \tmp[1][11] ;
  wire \tmp[1][12] ;
  wire \tmp[1][13] ;
  wire \tmp[1][14] ;
  wire \tmp[1][15] ;
  wire \tmp[1][1] ;
  wire \tmp[1][2] ;
  wire \tmp[1][3] ;
  wire \tmp[1][4] ;
  wire \tmp[1][5] ;
  wire \tmp[1][6] ;
  wire \tmp[1][7] ;
  wire \tmp[1][8] ;
  wire \tmp[1][9] ;
  wire \tmp[2][0] ;
  wire \tmp[2][10] ;
  wire \tmp[2][11] ;
  wire \tmp[2][12] ;
  wire \tmp[2][13] ;
  wire \tmp[2][14] ;
  wire \tmp[2][15] ;
  wire \tmp[2][1] ;
  wire \tmp[2][2] ;
  wire \tmp[2][3] ;
  wire \tmp[2][4] ;
  wire \tmp[2][5] ;
  wire \tmp[2][6] ;
  wire \tmp[2][7] ;
  wire \tmp[2][8] ;
  wire \tmp[2][9] ;
  assign \temp_tmp[1][2]   =  b[1] ? \tmp[0][0]  : \tmp[0][2] ;
  assign \temp_tmp[1][3]   =  b[1] ? \tmp[0][1]  : \tmp[0][3] ;
  assign \temp_tmp[1][4]   =  b[1] ? \tmp[0][2]  : \tmp[0][4] ;
  assign \temp_tmp[1][5]   =  b[1] ? \tmp[0][3]  : \tmp[0][5] ;
  assign \temp_tmp[1][6]   =  b[1] ? \tmp[0][4]  : \tmp[0][6] ;
  assign \temp_tmp[1][7]   =  b[1] ? \tmp[0][5]  : \tmp[0][7] ;
  assign \temp_tmp[1][8]   =  b[1] ? \tmp[0][6]  : \tmp[0][8] ;
  assign \temp_tmp[1][9]   =  b[1] ? \tmp[0][7]  : \tmp[0][9] ;
  assign \temp_tmp[1][10]   =  b[1] ? \tmp[0][8]  : \tmp[0][10] ;
  assign \temp_tmp[1][11]   =  b[1] ? \tmp[0][9]  : \tmp[0][11] ;
  assign \temp_tmp[1][12]   =  b[1] ? \tmp[0][10]  : \tmp[0][12] ;
  assign \temp_tmp[1][13]   =  b[1] ? \tmp[0][11]  : \tmp[0][13] ;
  assign \temp_tmp[1][14]   =  b[1] ? \tmp[0][12]  : \tmp[0][14] ;
  assign \temp_tmp[1][15]   =  b[1] ? \tmp[0][13]  : \tmp[0][15] ;
  assign \temp_tmp[2][0]   =  b[2] ? 1'h0 : \tmp[1][0] ;
  assign \temp_tmp[2][1]   =  b[2] ? 1'h0 : \tmp[1][1] ;
  assign \temp_tmp[2][2]   =  b[2] ? 1'h0 : \tmp[1][2] ;
  assign \temp_tmp[2][3]   =  b[2] ? 1'h0 : \tmp[1][3] ;
  assign \temp_tmp[2][4]   =  b[2] ? \tmp[1][0]  : \tmp[1][4] ;
  assign \temp_tmp[2][5]   =  b[2] ? \tmp[1][1]  : \tmp[1][5] ;
  assign \temp_tmp[2][6]   =  b[2] ? \tmp[1][2]  : \tmp[1][6] ;
  assign \temp_tmp[2][7]   =  b[2] ? \tmp[1][3]  : \tmp[1][7] ;
  assign \temp_tmp[2][8]   =  b[2] ? \tmp[1][4]  : \tmp[1][8] ;
  assign \temp_tmp[2][9]   =  b[2] ? \tmp[1][5]  : \tmp[1][9] ;
  assign \temp_tmp[2][10]   =  b[2] ? \tmp[1][6]  : \tmp[1][10] ;
  assign \temp_tmp[2][11]   =  b[2] ? \tmp[1][7]  : \tmp[1][11] ;
  assign \temp_tmp[2][12]   =  b[2] ? \tmp[1][8]  : \tmp[1][12] ;
  assign \temp_tmp[2][13]   =  b[2] ? \tmp[1][9]  : \tmp[1][13] ;
  assign \temp_tmp[2][14]   =  b[2] ? \tmp[1][10]  : \tmp[1][14] ;
  assign \temp_tmp[2][15]   =  b[2] ? \tmp[1][11]  : \tmp[1][15] ;
  assign temp_c[0]  =  b[3] ? 1'h0 : \tmp[2][0] ;
  assign temp_c[1]  =  b[3] ? 1'h0 : \tmp[2][1] ;
  assign temp_c[2]  =  b[3] ? 1'h0 : \tmp[2][2] ;
  assign temp_c[3]  =  b[3] ? 1'h0 : \tmp[2][3] ;
  assign temp_c[4]  =  b[3] ? 1'h0 : \tmp[2][4] ;
  assign temp_c[5]  =  b[3] ? 1'h0 : \tmp[2][5] ;
  assign temp_c[6]  =  b[3] ? 1'h0 : \tmp[2][6] ;
  assign temp_c[7]  =  b[3] ? 1'h0 : \tmp[2][7] ;
  assign temp_c[8]  =  b[3] ? \tmp[2][0]  : \tmp[2][8] ;
  assign temp_c[9]  =  b[3] ? \tmp[2][1]  : \tmp[2][9] ;
  assign temp_c[10]  =  b[3] ? \tmp[2][2]  : \tmp[2][10] ;
  assign temp_c[11]  =  b[3] ? \tmp[2][3]  : \tmp[2][11] ;
  assign temp_c[12]  =  b[3] ? \tmp[2][4]  : \tmp[2][12] ;
  assign temp_c[13]  =  b[3] ? \tmp[2][5]  : \tmp[2][13] ;
  assign temp_c[14]  =  b[3] ? \tmp[2][6]  : \tmp[2][14] ;
  assign temp_c[15]  =  b[3] ? \tmp[2][7]  : \tmp[2][15] ;
  assign \temp_tmp[0][0]   =  b[0] ? 1'h0 : a[0];
  assign \temp_tmp[0][1]   =  b[0] ? a[0] : a[1];
  assign \temp_tmp[0][2]   =  b[0] ? a[1] : a[2];
  assign \temp_tmp[0][3]   =  b[0] ? a[2] : a[3];
  assign \temp_tmp[0][4]   =  b[0] ? a[3] : a[4];
  assign \temp_tmp[0][5]   =  b[0] ? a[4] : a[5];
  assign \temp_tmp[0][6]   =  b[0] ? a[5] : a[6];
  assign \temp_tmp[0][7]   =  b[0] ? a[6] : a[7];
  assign \temp_tmp[0][8]   =  b[0] ? a[7] : a[8];
  assign \temp_tmp[0][9]   =  b[0] ? a[8] : a[9];
  assign \temp_tmp[0][10]   =  b[0] ? a[9] : a[10];
  assign \temp_tmp[0][11]   =  b[0] ? a[10] : a[11];
  assign \temp_tmp[0][12]   =  b[0] ? a[11] : a[12];
  assign \temp_tmp[0][13]   =  b[0] ? a[12] : a[13];
  assign \temp_tmp[0][14]   =  b[0] ? a[13] : a[14];
  assign \temp_tmp[0][15]   =  b[0] ? a[14] : a[15];
  assign \temp_tmp[1][0]   =  b[1] ? 1'h0 : \tmp[0][0] ;
  assign \temp_tmp[1][1]   =  b[1] ? 1'h0 : \tmp[0][1] ;
super_sabouter #(.WIDTH( 16 )) SS0(
                  .i_sig( temp_c ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[15:0] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( c ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS1(
                  .i_sig( \temp_tmp[0][0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[16:16] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS2(
                  .i_sig( \temp_tmp[0][10] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[17:17] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][10] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS3(
                  .i_sig( \temp_tmp[0][11] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[18:18] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][11] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS4(
                  .i_sig( \temp_tmp[0][12] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[19:19] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][12] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS5(
                  .i_sig( \temp_tmp[0][13] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[20:20] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][13] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS6(
                  .i_sig( \temp_tmp[0][14] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[21:21] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][14] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS7(
                  .i_sig( \temp_tmp[0][15] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[22:22] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][15] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS8(
                  .i_sig( \temp_tmp[0][1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[23:23] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS9(
                  .i_sig( \temp_tmp[0][2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[24:24] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS10(
                  .i_sig( \temp_tmp[0][3] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[25:25] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][3] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS11(
                  .i_sig( \temp_tmp[0][4] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[26:26] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][4] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS12(
                  .i_sig( \temp_tmp[0][5] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[27:27] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][5] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS13(
                  .i_sig( \temp_tmp[0][6] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[28:28] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][6] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS14(
                  .i_sig( \temp_tmp[0][7] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[29:29] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][7] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS15(
                  .i_sig( \temp_tmp[0][8] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[30:30] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][8] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS16(
                  .i_sig( \temp_tmp[0][9] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[31:31] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[0][9] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS17(
                  .i_sig( \temp_tmp[1][0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[32:32] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS18(
                  .i_sig( \temp_tmp[1][10] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[33:33] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][10] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS19(
                  .i_sig( \temp_tmp[1][11] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[34:34] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][11] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS20(
                  .i_sig( \temp_tmp[1][12] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[35:35] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][12] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS21(
                  .i_sig( \temp_tmp[1][13] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[36:36] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][13] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS22(
                  .i_sig( \temp_tmp[1][14] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[37:37] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][14] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS23(
                  .i_sig( \temp_tmp[1][15] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[38:38] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][15] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS24(
                  .i_sig( \temp_tmp[1][1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[39:39] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS25(
                  .i_sig( \temp_tmp[1][2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[40:40] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS26(
                  .i_sig( \temp_tmp[1][3] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[41:41] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][3] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS27(
                  .i_sig( \temp_tmp[1][4] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[42:42] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][4] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS28(
                  .i_sig( \temp_tmp[1][5] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[43:43] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][5] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS29(
                  .i_sig( \temp_tmp[1][6] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[44:44] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][6] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS30(
                  .i_sig( \temp_tmp[1][7] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[45:45] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][7] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS31(
                  .i_sig( \temp_tmp[1][8] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[46:46] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][8] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS32(
                  .i_sig( \temp_tmp[1][9] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[47:47] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[1][9] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS33(
                  .i_sig( \temp_tmp[2][0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[48:48] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS34(
                  .i_sig( \temp_tmp[2][10] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[49:49] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][10] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS35(
                  .i_sig( \temp_tmp[2][11] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[50:50] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][11] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS36(
                  .i_sig( \temp_tmp[2][12] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[51:51] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][12] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS37(
                  .i_sig( \temp_tmp[2][13] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[52:52] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][13] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS38(
                  .i_sig( \temp_tmp[2][14] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[53:53] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][14] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS39(
                  .i_sig( \temp_tmp[2][15] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[54:54] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][15] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS40(
                  .i_sig( \temp_tmp[2][1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[55:55] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS41(
                  .i_sig( \temp_tmp[2][2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[56:56] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS42(
                  .i_sig( \temp_tmp[2][3] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[57:57] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][3] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS43(
                  .i_sig( \temp_tmp[2][4] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[58:58] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][4] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS44(
                  .i_sig( \temp_tmp[2][5] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[59:59] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][5] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS45(
                  .i_sig( \temp_tmp[2][6] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[60:60] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][6] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS46(
                  .i_sig( \temp_tmp[2][7] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[61:61] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][7] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS47(
                  .i_sig( \temp_tmp[2][8] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[62:62] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][8] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS48(
                  .i_sig( \temp_tmp[2][9] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[63:63] ), 
                  .i_ctrl( o_SR[65:64] ), 
                  .o_sig( \tmp[2][9] ) 
                  );
shift_register #(.WIDTH(WIDTH_SR)) SR(
                    .i_CLK( i_FI_CONTROL_PORT[3] ),
                    .i_RST( i_FI_CONTROL_PORT[2] ),
                    .i_EN( i_FI_CONTROL_PORT[0] ),
                    .i_SI( i_SI ),
                    .o_DATA( o_SR )
                    );
endmodule
