/* Generated by Yosys 0.47+61 (git sha1 81011ad92, clang++ 18.1.8 -fPIC -O3) */

module \$paramod\LOD_N\N=s32'00000000000000000000000000010000_sbtr #(parameter WIDTH_SR = 54) (in, out, i_FI_CONTROL_PORT, i_SI, o_SI);
  input i_SI;
  input [3:0] i_FI_CONTROL_PORT;
  output o_SI;
  wire [WIDTH_SR-1:0] o_SR;
  assign o_SI = o_SR[0];
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0] ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1] ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0] ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1] ;
  wire \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.h.out[0] ;
  wire \temp_l1.genblk1.genblk1.h.out[1] ;
  wire \temp_l1.genblk1.genblk1.h.out[2] ;
  wire \temp_l1.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0] ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1] ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0] ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1] ;
  wire \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \temp_l1.genblk1.genblk1.l.out[0] ;
  wire \temp_l1.genblk1.genblk1.l.out[1] ;
  wire \temp_l1.genblk1.genblk1.l.out[2] ;
  wire \temp_l1.genblk1.genblk1.l.vld ;
  wire \temp_l1.out[0] ;
  wire \temp_l1.out[1] ;
  wire \temp_l1.out[2] ;
  wire \temp_l1.out[3] ;
  wire [3:0] temp_out ;
  input [15:0] in;
  wire [15:0] in;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0] ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1] ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0] ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1] ;
  wire \l1.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.h.out[0] ;
  wire \l1.genblk1.genblk1.h.out[1] ;
  wire \l1.genblk1.genblk1.h.out[2] ;
  wire \l1.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0] ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1] ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0] ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1] ;
  wire \l1.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  wire \l1.genblk1.genblk1.l.out[0] ;
  wire \l1.genblk1.genblk1.l.out[1] ;
  wire \l1.genblk1.genblk1.l.out[2] ;
  wire \l1.genblk1.genblk1.l.vld ;
  wire \l1.out[0] ;
  wire \l1.out[1] ;
  wire \l1.out[2] ;
  wire \l1.out[3] ;
  output [3:0] out;
  wire [3:0] out;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld   =  in[10] | in[11];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld   =  in[14] | in[15];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld   =  in[4] | in[5];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld   =  in[2] | in[3];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld   =  in[6] | in[7];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld   =  in[8] | in[9];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld   =  in[0] | in[1];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld   =  in[12] | in[13];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out  : \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out  : \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.l.out[0]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0]  : \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0] ;
  assign \temp_l1.genblk1.genblk1.l.out[1]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1]  : \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1] ;
  assign \temp_l1.genblk1.genblk1.l.out[2]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out  : \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out  : \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1]   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  assign \temp_l1.out[0]   =  \l1.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.out[0]  : \l1.genblk1.genblk1.l.out[0] ;
  assign \temp_l1.out[1]   =  \l1.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.out[1]  : \l1.genblk1.genblk1.l.out[1] ;
  assign \temp_l1.out[2]   =  \l1.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.out[2]  : \l1.genblk1.genblk1.l.out[2] ;
  assign \temp_l1.out[3]   =  \l1.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.h.out[0]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0]  : \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0] ;
  assign \temp_l1.genblk1.genblk1.h.out[1]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1]  : \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1] ;
  assign \temp_l1.genblk1.genblk1.h.out[2]   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld  ? 1'h0 : \l1.genblk1.genblk1.h.genblk1.genblk1.l.vld ;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_   =  ~in[11];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_   =  ~in[9];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_   =  ~in[15];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_   =  ~in[13];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_   =  ~in[3];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_   =  ~in[1];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_   =  ~in[7];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_   =  ~in[5];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_  & in[10];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_  & in[8];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.vld   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_  & in[14];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_  & in[12];
  assign \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.vld   =  \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  assign \temp_l1.genblk1.genblk1.l.vld   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_  & in[2];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_  & in[0];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.vld   =  \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld ;
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_  & in[6];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_  & in[4];
  assign \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.vld   =  \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  assign \temp_l1.genblk1.genblk1.h.vld   =  \l1.genblk1.genblk1.h.genblk1.genblk1.l.vld  | \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld ;
  assign temp_out  =  { \l1.out[3] , \l1.out[2] , \l1.out[1] , \l1.out[0]  };
super_sabouter #(.WIDTH( 1 )) SS0(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[0:0] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS1(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[1:1] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS2(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[2:2] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS3(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[3:3] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS4(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[4:4] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS5(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[5:5] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS6(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[6:6] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS7(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[7:7] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS8(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[8:8] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS9(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[9:9] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS10(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[10:10] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS11(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[11:11] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS12(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[12:12] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS13(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[13:13] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS14(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[14:14] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS15(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[15:15] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS16(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[16:16] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS17(
                  .i_sig( \temp_l1.genblk1.genblk1.h.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[17:17] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS18(
                  .i_sig( \temp_l1.genblk1.genblk1.h.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[18:18] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS19(
                  .i_sig( \temp_l1.genblk1.genblk1.h.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[19:19] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS20(
                  .i_sig( \temp_l1.genblk1.genblk1.h.out[2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[20:20] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.out[2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS21(
                  .i_sig( \temp_l1.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[21:21] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS22(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[22:22] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS23(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[23:23] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS24(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[24:24] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS25(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[25:25] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS26(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[26:26] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS27(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[27:27] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS28(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[28:28] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS29(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[29:29] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS30(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[30:30] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS31(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[31:31] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS32(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[32:32] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS33(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[33:33] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.h.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS34(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[34:34] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.out ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS35(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[35:35] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.rtil_signal_0_ ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS36(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[36:36] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS37(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[37:37] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS38(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[38:38] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS39(
                  .i_sig( \temp_l1.genblk1.genblk1.l.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[39:39] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS40(
                  .i_sig( \temp_l1.genblk1.genblk1.l.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[40:40] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS41(
                  .i_sig( \temp_l1.genblk1.genblk1.l.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[41:41] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS42(
                  .i_sig( \temp_l1.genblk1.genblk1.l.out[2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[42:42] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.out[2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS43(
                  .i_sig( \temp_l1.genblk1.genblk1.l.vld ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[43:43] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.genblk1.genblk1.l.vld ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS44(
                  .i_sig( \temp_l1.out[0] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[44:44] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.out[0] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS45(
                  .i_sig( \temp_l1.out[1] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[45:45] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.out[1] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS46(
                  .i_sig( \temp_l1.out[2] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[46:46] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.out[2] ) 
                  );
super_sabouter #(.WIDTH( 1 )) SS47(
                  .i_sig( \temp_l1.out[3] ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[47:47] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( \l1.out[3] ) 
                  );
super_sabouter #(.WIDTH( 4 )) SS48(
                  .i_sig( temp_out ), 
                  .i_en_super_sabouter( i_FI_CONTROL_PORT[1] ), 
                  .i_en_basic_sabouter( o_SR[51:48] ), 
                  .i_ctrl( o_SR[53:52] ), 
                  .o_sig( out ) 
                  );
shift_register #(.WIDTH(WIDTH_SR)) SR(
                    .i_CLK( i_FI_CONTROL_PORT[3] ),
                    .i_RST( i_FI_CONTROL_PORT[2] ),
                    .i_EN( i_FI_CONTROL_PORT[0] ),
                    .i_SI( i_SI ),
                    .o_DATA( o_SR )
                    );
endmodule
